version: '3.8'

services:
  builder:
    image: remoorejr/alpha-cordova-android-build:latest
    container_name: cordova-builder
    user: cordovauser
    working_dir: /home/cordovauser/app
    volumes:
      # 1. Bind mount for your source code (Windows <-> Container)
      - .:/home/cordovauser/app
      
      # 2. Anonymous volume to prevent Windows permission issues on the config folder
      - /home/cordovauser/.config

      # 3. Named volumes for high-performance caching (Stored inside Docker's Linux VM)
      - gradle_cache:/home/cordovauser/.gradle
      - npm_cache:/home/cordovauser/.npm

    environment:
    
      - GIT_USER_NAME=Your Name
      - GIT_USER_EMAIL=your@email.com
    
    # Keeps the container interactive for ADB and terminal access
    tty: true
    stdin_open: true

# volumes
volumes:
  gradle_cache:
  npm_cache: